"""init 1

Revision ID: 271e5267ad88
Revises: 
Create Date: 2025-03-16 10:51:05.818610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '271e5267ad88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_to', sa.Integer(), nullable=False),
    sa.Column('id_from', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('path', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('organization', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fio', sa.String(length=100), nullable=False),
    sa.Column('post', sa.String(length=50), nullable=False),
    sa.Column('level_skill', sa.Integer(), nullable=False),
    sa.Column('speciality', sa.String(length=200), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('ability', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscribe', sa.Boolean(), nullable=False),
    sa.Column('code_word', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['level_skill'], ['level_skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('publication_date', mysql.DATETIME(), nullable=True),
    sa.Column('date_begin', sa.DATE(), nullable=True),
    sa.Column('date_end', sa.DATE(), nullable=True),
    sa.Column('level_skill', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('id_employer', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['id_employer'], ['employers.id'], ),
    sa.ForeignKeyConstraint(['level_skill'], ['level_skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('id_vacancy', sa.Integer(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_status'], ['statuses.id'], ),
    sa.ForeignKeyConstraint(['id_student'], ['students.id'], ),
    sa.ForeignKeyConstraint(['id_vacancy'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('id_vacancy', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DATE(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_student'], ['students.id'], ),
    sa.ForeignKeyConstraint(['id_vacancy'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('id_vacancy', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('path_type', sa.Integer(), nullable=True),
    sa.Column('date_publicated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_student'], ['students.id'], ),
    sa.ForeignKeyConstraint(['id_vacancy'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('interview')
    op.drop_table('applications')
    op.drop_table('vacancies')
    op.drop_table('students')
    op.drop_table('employers')
    op.drop_table('users')
    op.drop_table('statuses')
    op.drop_table('level_skills')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
